// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: api/v1/analyticapr.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// https://docs.github.com/ja/graphql/reference/enums#pullrequestreviewstate
type Review_State int32

const (
	Review_STATE_UNSPECIFIED Review_State = 0
	Review_STATE_APPROVED    Review_State = 1
	Review_STATE_COMMENTED   Review_State = 3
)

// Enum value maps for Review_State.
var (
	Review_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_APPROVED",
		3: "STATE_COMMENTED",
	}
	Review_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_APPROVED":    1,
		"STATE_COMMENTED":   3,
	}
)

func (x Review_State) Enum() *Review_State {
	p := new(Review_State)
	*p = x
	return p
}

func (x Review_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Review_State) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_analyticapr_proto_enumTypes[0].Descriptor()
}

func (Review_State) Type() protoreflect.EnumType {
	return &file_api_v1_analyticapr_proto_enumTypes[0]
}

func (x Review_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Review_State.Descriptor instead.
func (Review_State) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_analyticapr_proto_rawDescGZIP(), []int{1, 0}
}

type Comment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author string `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
}

func (x *Comment) Reset() {
	*x = Comment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_analyticapr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analyticapr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_api_v1_analyticapr_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

type Review struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Author string       `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	State  Review_State `protobuf:"varint,2,opt,name=state,proto3,enum=api.v1.Review_State" json:"state,omitempty"`
}

func (x *Review) Reset() {
	*x = Review{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_analyticapr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Review) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Review) ProtoMessage() {}

func (x *Review) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analyticapr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Review.ProtoReflect.Descriptor instead.
func (*Review) Descriptor() ([]byte, []int) {
	return file_api_v1_analyticapr_proto_rawDescGZIP(), []int{1}
}

func (x *Review) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Review) GetState() Review_State {
	if x != nil {
		return x.State
	}
	return Review_STATE_UNSPECIFIED
}

type PullRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number   int32      `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Title    string     `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author   string     `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Comments []*Comment `protobuf:"bytes,4,rep,name=comments,proto3" json:"comments,omitempty"`
	Reviews  []*Review  `protobuf:"bytes,5,rep,name=reviews,proto3" json:"reviews,omitempty"`
}

func (x *PullRequest) Reset() {
	*x = PullRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_analyticapr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullRequest) ProtoMessage() {}

func (x *PullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analyticapr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullRequest.ProtoReflect.Descriptor instead.
func (*PullRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_analyticapr_proto_rawDescGZIP(), []int{2}
}

func (x *PullRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *PullRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PullRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PullRequest) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *PullRequest) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

type RepositoryAnalytica struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repository *Repository    `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Pulls      []*PullRequest `protobuf:"bytes,2,rep,name=pulls,proto3" json:"pulls,omitempty"`
}

func (x *RepositoryAnalytica) Reset() {
	*x = RepositoryAnalytica{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_analyticapr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RepositoryAnalytica) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryAnalytica) ProtoMessage() {}

func (x *RepositoryAnalytica) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analyticapr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryAnalytica.ProtoReflect.Descriptor instead.
func (*RepositoryAnalytica) Descriptor() ([]byte, []int) {
	return file_api_v1_analyticapr_proto_rawDescGZIP(), []int{3}
}

func (x *RepositoryAnalytica) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *RepositoryAnalytica) GetPulls() []*PullRequest {
	if x != nil {
		return x.Pulls
	}
	return nil
}

type Analyticapr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repositories []*RepositoryAnalytica `protobuf:"bytes,1,rep,name=repositories,proto3" json:"repositories,omitempty"`
}

func (x *Analyticapr) Reset() {
	*x = Analyticapr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_v1_analyticapr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Analyticapr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Analyticapr) ProtoMessage() {}

func (x *Analyticapr) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_analyticapr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Analyticapr.ProtoReflect.Descriptor instead.
func (*Analyticapr) Descriptor() ([]byte, []int) {
	return file_api_v1_analyticapr_proto_rawDescGZIP(), []int{4}
}

func (x *Analyticapr) GetRepositories() []*RepositoryAnalytica {
	if x != nil {
		return x.Repositories
	}
	return nil
}

var File_api_v1_analyticapr_proto protoreflect.FileDescriptor

var file_api_v1_analyticapr_proto_rawDesc = []byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x61, 0x70, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x1a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x21, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0x95, 0x01, 0x0a, 0x06, 0x52,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x2a, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x44, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x43, 0x4f, 0x4d, 0x4d, 0x45, 0x4e, 0x54, 0x45, 0x44,
	0x10, 0x03, 0x22, 0xaa, 0x01, 0x0a, 0x0b, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x08, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73,
	0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x07, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x22,
	0x74, 0x0a, 0x13, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x6e, 0x61,
	0x6c, 0x79, 0x74, 0x69, 0x63, 0x61, 0x12, 0x32, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x0a,
	0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x05, 0x70, 0x75,
	0x6c, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05,
	0x70, 0x75, 0x6c, 0x6c, 0x73, 0x22, 0x4e, 0x0a, 0x0b, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69,
	0x63, 0x61, 0x70, 0x72, 0x12, 0x3f, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x41, 0x6e,
	0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x61, 0x52, 0x0c, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x6f, 0x6b, 0x61, 0x6d, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x74, 0x69, 0x63, 0x61, 0x70, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_v1_analyticapr_proto_rawDescOnce sync.Once
	file_api_v1_analyticapr_proto_rawDescData = file_api_v1_analyticapr_proto_rawDesc
)

func file_api_v1_analyticapr_proto_rawDescGZIP() []byte {
	file_api_v1_analyticapr_proto_rawDescOnce.Do(func() {
		file_api_v1_analyticapr_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_v1_analyticapr_proto_rawDescData)
	})
	return file_api_v1_analyticapr_proto_rawDescData
}

var file_api_v1_analyticapr_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_analyticapr_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_analyticapr_proto_goTypes = []interface{}{
	(Review_State)(0),           // 0: api.v1.Review.State
	(*Comment)(nil),             // 1: api.v1.Comment
	(*Review)(nil),              // 2: api.v1.Review
	(*PullRequest)(nil),         // 3: api.v1.PullRequest
	(*RepositoryAnalytica)(nil), // 4: api.v1.RepositoryAnalytica
	(*Analyticapr)(nil),         // 5: api.v1.Analyticapr
	(*Repository)(nil),          // 6: api.v1.Repository
}
var file_api_v1_analyticapr_proto_depIdxs = []int32{
	0, // 0: api.v1.Review.state:type_name -> api.v1.Review.State
	1, // 1: api.v1.PullRequest.comments:type_name -> api.v1.Comment
	2, // 2: api.v1.PullRequest.reviews:type_name -> api.v1.Review
	6, // 3: api.v1.RepositoryAnalytica.repository:type_name -> api.v1.Repository
	3, // 4: api.v1.RepositoryAnalytica.pulls:type_name -> api.v1.PullRequest
	4, // 5: api.v1.Analyticapr.repositories:type_name -> api.v1.RepositoryAnalytica
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_analyticapr_proto_init() }
func file_api_v1_analyticapr_proto_init() {
	if File_api_v1_analyticapr_proto != nil {
		return
	}
	file_api_v1_config_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_v1_analyticapr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Comment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_analyticapr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Review); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_analyticapr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PullRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_analyticapr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RepositoryAnalytica); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_v1_analyticapr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Analyticapr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_v1_analyticapr_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_analyticapr_proto_goTypes,
		DependencyIndexes: file_api_v1_analyticapr_proto_depIdxs,
		EnumInfos:         file_api_v1_analyticapr_proto_enumTypes,
		MessageInfos:      file_api_v1_analyticapr_proto_msgTypes,
	}.Build()
	File_api_v1_analyticapr_proto = out.File
	file_api_v1_analyticapr_proto_rawDesc = nil
	file_api_v1_analyticapr_proto_goTypes = nil
	file_api_v1_analyticapr_proto_depIdxs = nil
}
